services:
  webserver:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:docker
    environment:
      PORT: 8000
